name: headset_connection_event
description: Flutter Plugin for headset events. Detect headset is plugged and unplugged. Get current headset state.
version: 2.0.1
homepage: https://github.com/GitStartHQ/popsical_heaset_event

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: flutter.moum.headset_connection_event
        pluginClass: HeadsetConnectionEventPlugin
      ios:
        pluginClass: HeadsetConnectionEventPlugin
